App/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from Project import settings
from .views import (HomePage, AboutPage, FeedPage, FeedDetail, FeedCreate,
                    FeedUpdate, FeedDelete, CommentCreate, CommentUpdate,
                    CommentDelete, ReplyCreate)

urlpatterns = [
    path('',HomePage.as_view(), name='Home'),
    path('about/', AboutPage.as_view(), name='About'),
    path('feed/', FeedPage.as_view(), name='Feed'),
    path('feed/<int:pk>', FeedDetail.as_view(), name='Feed_Detail'),
    path('feed/new', FeedCreate.as_view(), name='Feed_Create'),
    path('feed/<int:pk>/edit', FeedUpdate.as_view(), name='Feed_Update'),
    path('feed/<int:pk>/delete', FeedDelete.as_view(), name='Feed_Delete'),
    path('feed/<int:pk>/comment', CommentCreate.as_view(), name='Comment_Create'),
    path('feed/<int:post_pk>/comment/<int:pk>/update', CommentUpdate.as_view(),name='Comment_Update'),
    path('feed/<int:post_pk>/comment/<int:pk>/delete', CommentDelete.as_view(), name='Comment_Delete'),
    path('post/<int:pk>/comment/<int:comment_id>/reply/', ReplyCreate.as_view(), name='Reply_Create'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

App/models.py
from django.db import models
from django.template.context_processors import media
from django.urls import reverse
from django.conf import settings


class Artist(models.Model):
    username = models.CharField(max_length=200)
    email = models.EmailField()
    profile_pic = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.username

class Category(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField (null=True, blank=True, upload_to='images/')
    artist = models.ManyToManyField("Artist", related_name="artists")
    category = models.ForeignKey("Category", on_delete=models.CASCADE, null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    published_date = models.DateTimeField(auto_now=True, blank=True, null=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "Feed_Detail",
            kwargs={
                "pk": self.pk
            })

class Comment(models.Model):
    post = models.ForeignKey("Post",related_name="comments", on_delete=models.CASCADE)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

def __str__(self):
        return '%s - %s' % (self.post.title, self.username)

App/templates/app/Feed/feed.html
{% extends 'App/index.html' %}
{% block content %}
    <div class="CreatePost">

{% if user.is_authenticated%}
    <h3><a href="{% url 'Feed_Create' %}">Create Post </a></h3>
{% else %}
    <h3>Log in to create a post.</h3>
    {% endif %}

</div>
    <hr>
    <div class="card-container">
        {% for post in posts %}
            <div class="post-container">
                {% if post.image %}
                    <div class="post-image-container">
                        <img class="post-image" src="{{ post.image.url }}" alt="{{ post.title }}">
                    </div>
                {% else %}
                    <div class="no-image-container">
                        <p class="no-image">No image available</p>
                    </div>
                {% endif %}

                <div class="post-details">
                    <h3 class="post-title">
                        <span class="post-user">{{ post.user }}</span> <br>
                        <a href="{% url 'Feed_Detail' post.pk %}">{{ post.title }}</a>
                    </h3>
                    <p class="post-text">{{ post.text }}</p>
                </div>
            </div>
        {% empty %}
            <div class="no-posts-container">
                <p>No posts available.</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

App/templates/app/Feed/feed_create.html
{% extends 'App/index.html' %}
{% load static %}
{% block content %}
    <h1>Create Feed</h1>

<div>
    <form action="{% url 'Feed_Create' %}" method="post" enctype="multipart/form-data" class="custom-form">
        {% csrf_token %}

        <div class="title-upload">
            <label for="id_title">Title:</label>
            <input type="text" name="title" id="id_title">
        </div>

        <div class="text-upload">
            <label for="id_text">Text:</label>
            <input type="text" name="text" id="id_text">
        </div>

        <div class="user-upload">
            <label for="id_user">user:</label>
            <select id="id_user" name="user">
                {% for user in users %}
                    <option value="{{ user.id }}" {% if user.id == form.user.value %}selected{% endif %}>
                        {{ user }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div class="image-upload">
            <label for="id_image">Image:</label>
            <input type="file" name="image" id="id_image" onchange="previewFile(this)">
            <br>
            <img id="imagePreview" src="{{ post.image.url }}" alt="Image Preview"
                 style="max-width: 400px; margin-top: 10px; display: none;">
        </div>

        <div class="artist-upload">
            <label for="id_artist">Artist:</label>
            <select id="id_artist" name="artist">
                {% for artist in artists %}
                    <option value="{{ artist.id }}" {% if artist.id == form.artist.value %}selected{% endif %}>
                        {{ artist }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="category-upload">
            <label for="id_category">Category:</label>
            <select id="id_category" name="category">
                {% for category in categories %}
                    <option value="{{ category.id }}" {% if category.id == form.category.value %}selected{% endif %}>
                        {{ category }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <input type="submit" value="Create">
    </form>

</div>

{% endblock %}

App/templates/app/Feed/feed_delete.html
{% extends 'App/index.html' %}
{% block content %}
    <h1>Edit post</h1>

    <form action="{% url 'Feed_Delete' post.pk %}" method="post" class="custom-form">
        {% csrf_token %}
        <p>Are you sure you want to delete this "{{ post.title }}"?</p>
        <input type="submit" value="Delete">
        <a href="{% url 'Feed_Detail' post.pk  %}">Back</a>
    </form>

{% endblock %}

App/templates/app/Feed/feed_detail.html
{% extends 'App/index.html' %}
{% load static %}

{% block content %}

<div class="Detail">
    <div class="feed-detail">

        <div class="Back">
            <input type="button" value="X" onclick="history.back()" class="input_button" style="Font-size: 20px; color: white; background-color:#3b82f6">
        </div>

        <div class="feed-detail-header">
            <h1>{{ post.title }}</h1>
            <p>{{ post.body }}</p>
            <p>Category: {{ post.category }}</p>
            <p>Posted by: {{ post.user }}</p>
            <p>Posted on: {{ post.created_date }}</p>
        </div>

        <div class="feed-detail-image">
            {% if post.image %}
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
            {% else %}
                <p>No image</p>
            {% endif %}
        </div>
    </div>

    <div class="feed-detail-edit">
        <a href="{% url 'Feed_Update' post.id %}">Edit post</a>
        <a href="{% url 'Feed_Delete' post.id %}">Delete post</a>
    </div>

    <hr>

<div class="feed-detail-comment">
    <div class="comments-header">
        <h2>Comments...</h2>
        <form method="POST" action="{% url 'Comment_Create' post.pk %}">
            {% csrf_token %}
            <textarea name="body" cols="110" rows="2" placeholder="Write a comment..." required></textarea>
            <input type="submit" value="Post Comment">
        </form>
    </div>

    <div class="comments-list">
        {% if not post.comments.all %}
            <p>No comments yet.</p>
        {% else %}
            <div class="comments-list-detail">
                {% for comment in post.comments.all %}
                    <hr>
                    <p><strong>{{ comment.username }}</strong> - {{ comment.created_on }}</p>
                    <p>{{ comment.body }}</p>
                    <a href="{% url 'Comment_Update' post.pk comment.id %}">Edit Comment</a>
                    <br>
                    <a href="{% url 'Comment_Delete' post.pk comment.id %}">Delete Comment</a>
                    <br>
                    <a href="#" class="reply-link" data-comment-id="{{ comment.id }}">Reply</a>
                    <div class="reply-form" id="reply-form-{{ comment.id }}">
                        <form method="POST" action="{% url 'Reply_Create' post.pk comment.id %}">
                            {% csrf_token %}
                            <input type="text" name="body" placeholder="Write a reply..." required>
                            <input  type="submit" value="Post Reply">
                        </form>
                    </div>
                    <div class="replies-list">
                        {% for reply in comment.replies.all %}
                            <div class="reply-item">
                                <p><strong>{{ reply.username }}</strong> - {{ reply.created_on }}</p>
                                <p>{{ reply.body }}</p>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>

    <hr>
</div>
<script>
    document.querySelectorAll('.reply-link').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            const commentId = this.getAttribute('data-comment-id');
            document.getElementById(`reply-form-${commentId}`).style.display = 'block';
        });
    });
</script>
{% endblock %}

App/templates/app/Feed/feed_update.html
{% extends 'App/index.html' %}
{% block content %}
    <a href="{% url 'Feed' %}">Back</a>
    <h1>Edit Post</h1>

    <form action="{% url 'Feed_Update' object.pk %}" method="post" enctype="multipart/form-data" class="custom-form">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}